# build image
# push image
# kustomize
# commit new image
# push commit
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - -t
  - gcr.io/$PROJECT_ID/demo:$SHORT_SHA
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - gcr.io/$PROJECT_ID/demo:$SHORT_SHA
- name: nekottyo/kustomize-kubeval
  entrypoint: kustomize
  args:
  - edit
  - set
  - image
  - demo=gcr.io/$PROJECT_ID/demo:$SHORT_SHA
- name: google/cloud-sdk:alpine
  entrypoint: git
  args:
  - add
  - manifests/kustomization.yaml
- name: google/cloud-sdk:alpine
  entrypoint: git
  args:
  - commit
  - -m
  - "Update image to $SHORT_SHA"
- name: google/cloud-sdk:alpine
  entrypoint: git
  args:
  - push
