# build image
# push image
# kustomize
# commit new image
# push commit
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - -t
  - gcr.io/$PROJECT_ID/demo:$SHORT_SHA
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - gcr.io/$PROJECT_ID/demo:$SHORT_SHA
- name: nekottyo/kustomize-kubeval
  entrypoint: kustomize
  dir: manifests
  args:
  - edit
  - set
  - image
  - demo=gcr.io/$PROJECT_ID/demo:$SHORT_SHA
- name: google/cloud-sdk:alpine
  entrypoint: bash
  args:
  - -c
  - |-
    git config user.email joshuah9519@gmail.com
    git config user.name Cloud Build
    git pull origin main
    git checkout main
    git add manifests/kustomization.yaml
    git commit -m 'Update image to $SHORT_SHA'
    git push
