apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
- namespace.yaml
- deploy.yaml
- ingress.yaml
- svc.yaml
images:
- name: demo
  newName: gcr.io/netlify-dns-test/demo
  newTag: 2b0bdc9
